<template>
    <section>
        <ul class="list">
            <NuxtLink  v-for="post in posts" :key="post.attributes.title" :to="post.attributes.slug" >
                <li>
                    <div class="hero_image">
                        <img :src="post.attributes.hero_image" :alt="post.attributes.title">
                    </div>
                    <div class="blogList__info">
                        <h2>{{ post.attributes.title }}</h2>
                        <h3>{{ new Date(post.attributes.date).toDateString().slice(4) }}</h3>
                        <p >{{ post.body.slice(0 , 200).trimEnd()}}...</p>
                    </div>
                </li>
            </NuxtLink>                  
        </ul>
    </section>                       
</template>
<script>
    export default {
        props: ['posts'], 
    }
</script>

/* 
I would really love to figure out how to do this simple thing
how to make that link :to dynamically get the slug or how to use this
props data to generated computed values for each post that has the manipulated
slug. this should be simple...for whatever reason i couldn't figure it out. 
I tried using the props to add a generateSlugs() function with computed values.
I tried using a template string, concatonation, { path: ""} what have you....
its really annoying to not be able to use template strings here
so for now the solve is to just be really careful with the slugs and have those be entered
in the frontmatter...i wonder if I can make the slug generation happen automatically or behind
the scenes and not have that be something generated by users on forestry

#2 - i would love to figure out how to show the md in the summary... right now its just plaintext
 */



